use ci6206;


/** Drop tables */
DROP TABLE IF EXISTS `TB_USER_ROLE`;
DROP TABLE IF EXISTS `TB_ROLE_PERMISSION`;
DROP TABLE IF EXISTS `TB_ROLE`;
DROP TABLE IF EXISTS `TB_PERMISSION`;


/** Create table TB_PERMISSION*/
CREATE TABLE TB_PERMISSION (
	NBR BIGINT(19),
	ACTION_DESC VARCHAR(200) NOT NULL,
	PERMISSION_NAME VARCHAR(200) NOT NULL,
	PERMISSION_DESC VARCHAR(200),
	PRIMARY KEY (NBR)
);

/** Create table TB_ROLE */
CREATE TABLE TB_ROLE (
	NBR BIGINT(19),
	ROLE_NAME VARCHAR(200) NOT NULL,
	ROLE_DESC VARCHAR(200),
	PRIMARY KEY (NBR)
);

/** Create table TB_ROLE_PERMISSION */
CREATE TABLE TB_ROLE_PERMISSION (
	ROLE_NBR BIGINT(19) NOT NULL,
	PERMISSION_NBR BIGINT(19) NOT NULL,
	PRIMARY KEY (ROLE_NBR, PERMISSION_NBR),
	FOREIGN KEY (ROLE_NBR) 
        REFERENCES TB_ROLE(NBR)
        ON DELETE CASCADE,
	FOREIGN KEY (PERMISSION_NBR) 
        REFERENCES TB_PERMISSION(NBR)
        ON DELETE CASCADE
);

/** Create table TB_USER_ROLE */
CREATE TABLE TB_USER_ROLE (
	USER_ID varchar(25) NOT NULL,
	ROLE_NBR BIGINT(19) NOT NULL,
	PRIMARY KEY (USER_ID, ROLE_NBR),
	FOREIGN KEY (ROLE_NBR) 
        REFERENCES TB_ROLE(NBR)
        ON DELETE CASCADE
);

/** Insert Permission for USER, ROLE AND PERMISSION models */
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(1,'LIST','USER','List Users');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(2,'CREATE','USER','Create User');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(3,'DELETE','USER','Delete Users');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(4, 'EDIT','USER','Edit User');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(5,'LIST','ROLE','List Roles');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(6,'CREATE','ROLE','Create Role');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(7,'DELETE','ROLE','Delete Role');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(8, 'EDIT','ROLE','Edit Role');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(9,'LIST','PERMISSION','List Permissions');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(10,'CREATE','PERMISSION','Create Permission');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(11,'DELETE','PERMISSION','Delete Permission');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(12, 'EDIT','PERMISSION','Edit Permission');
INSERT INTO TB_PERMISSION (NBR, ACTION_DESC,PERMISSION_NAME,PERMISSION_DESC)
	VALUES(13, 'VIEW','ADMIN','View Admin Menu');

/** Insert ADMIN role */
INSERT INTO TB_ROLE (nbr, role_name, role_desc) VALUES (1, 'ADMIN', 'ADMIN ROLE');

/** Assign permissions to ADMIN role. */
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 1);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 2);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 3);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 4);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 5);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 6);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 7);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 8);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 9);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 10);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 11);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 12);
INSERT INTO TB_ROLE_PERMISSION (ROLE_NBR, PERMISSION_NBR)
	VALUES (1, 13);
	
/** Assign ADMIN role to Admin user. */
INSERT INTO TB_USER_ROLE (USER_ID, ROLE_NBR)
	VALUES ('admin', 1);